export const LOGIN_ROUTE = "/"
export const REGISTER_ROUTE = "/signup"
export const CHAT_ROUTE = "/chat"
export const PROFILE_ROUTE = "/profile"
export const SETTINGS_ROUTE = "/settings"
export const FRIENDS_ROUTE = "/friends"
